import "@/app/ui/globals.css";
import { inter } from "@/app/ui/fonts";

export const metadata = {
  title: "Spenderly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
